clone_depth: 10

environment:

  BOOST_PROG_OPTION: "C:/projects/ensmallen/\
  boost_program_options-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
  BOOST_MATH: "C:/projects/ensmallen/\
  boost_math_c99-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
  BOOST_RANDOM: "C:/projects/ensmallen/\
  boost_random-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
  BOOST_SERIALIZATION: "C:/projects/ensmallen/\
  boost_serialization-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
  BOOST_UNIT_TEST: "C:/projects/ensmallen/\
  boost_unit_test_framework-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
  ARMADILLO_INCLUDE: "C:/projects/ensmallen/armadillo-7.800.2/include"
  ARMADILLO_LIBRARY: "C:/projects/ensmallen/armadillo-7.800.2/\
  build/Debug/armadillo.lib"
  BLAS_LIBRARY: "C:/projects/ensmallen/OpenBLAS.0.2.14.1/lib/native/lib/x64/\
  libopenblas.dll.a"
  MLPACK_DIR: "C:/projects/mlpack"
  MLPACK_LIBRARY: "C:/projects/mlpack/build/Release/mlpack.lib"
  MLPACK_INCLUDE: "C:/projects/mlpack/build/include"
  BOOST_INCLUDE: "C:/projects/ensmallen/boost.1.60.0.0/lib/native/include"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VSVER: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSVER: Visual Studio 15 2017 Win64

configuration: Release

os: Visual Studio 2015

install:
  - ps: cd C:\projects
  - ps: git clone -q --depth=2 --branch=master https://github.com/mlpack/mlpack.git C:\projects\mlpack 2>$null
  - ps: nuget install boost -o %MLPACK_DIR% -Version 1.60.0
  - ps: >
      nuget install boost_unit_test_framework-vc140
      -o %MLPACK_DIR% -Version 1.60.0
  - ps: >
      nuget install boost_program_options-vc140
      -o %MLPACK_DIR% -Version 1.60.0
  - ps: >
      nuget install boost_random-vc140
      -o %MLPACK_DIR% -Version 1.60.0
  - ps: >
      nuget install boost_serialization-vc140
      -o %MLPACK_DIR% -Version 1.60.0
  - ps: >
      nuget install boost_math_c99-vc140
      -o %MLPACK_DIR% -Version 1.60.0
  - ps: nuget install OpenBLAS -o %MLPACK_DIR%

build_script:
  # build mlpack
  - cd C:\projects\mlpack
  - mkdir boost_libs
  - ps: cp ${env:BOOST_PROG_OPTION} C:\projects\mlpack\boost_libs\
  - ps: cp ${env:BOOST_MATH} C:\projects\mlpack\boost_libs\
  - ps: cp ${env:BOOST_RANDOM} C:\projects\mlpack\boost_libs\
  - ps: cp ${env:BOOST_SERIALIZATION} C:\projects\mlpack\boost_libs\
  - ps: cp ${env:BOOST_UNIT_TEST} C:\projects\mlpack\boost_libs\
  - if not exist armadillo.tar.xz appveyor DownloadFile "http://sourceforge.net/projects/arma/files/armadillo-7.800.2.tar.xz" -FileName armadillo.tar.xz
  - 7z x armadillo.tar.xz -so | 7z x -si -ttar > nul
  - cd armadillo-7.800.2 && mkdir build && cd build
  - >
    cmake -G "Visual Studio 14 2015 Win64"
    -DBLAS_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DLAPACK_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DCMAKE_PREFIX:FILEPATH="C:/projects/mlpack/armadillo"
    -DBUILD_SHARED_LIBS=OFF
    -DCMAKE_BUILD_TYPE=Release ..
  - cd C:\projects\mlpack && mkdir build && cd build
  - >
    cmake -G "Visual Studio 14 2015 Win64"
    -DBLAS_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DLAPACK_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DARMADILLO_INCLUDE_DIR=%ARMADILLO_INCLUDE%
    -DARMADILLO_LIBRARY:FILEPATH=%ARMADILLO_LIBRARY%
    -DBOOST_INCLUDEDIR:PATH=%BOOST_INCLUDE%
    -DBOOST_LIBRARYDIR:PATH="C:/projects/mlpack/boost_libs"
    -DDEBUG=OFF
    -DPROFILE=OFF
    -DBUILD_PYTHON_BINDINGS=OFF
    -DCMAKE_BUILD_TYPE=Release ..
  - >
    7z a mlpack-windows-no-libs.zip
    "%APPVEYOR_BUILD_FOLDER%\build\Release\*.exe"
  - >
    7z a mlpack-windows.zip
    "C:/projects/mlpack/build/Release/*.*"
    "C:/projects/mlpack/OpenBLAS.0.2.14.1/lib/native/lib/x64/*.*"

  # build models
  - cd C:\projects\models && mkdir build && cd build
  - >
    cmake -G "Visual Studio 14 2015 Win64"
    -DBLAS_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DLAPACK_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DARMADILLO_INCLUDE_DIR=%ARMADILLO_INCLUDE%
    -DARMADILLO_LIBRARY:FILEPATH=%ARMADILLO_LIBRARY%
    -DBOOST_INCLUDEDIR:PATH=%BOOST_INCLUDE%
    -DBOOST_LIBRARYDIR:PATH="C:\projects\mlpack\boost_libs"
    -DMLPACK_LIBRARY:FILEPATH=%MLPACK_LIBRARY%
    -DMLPACK_INCLUDE_DIR:PATH=%MLPACK_INCLUDE%
    -DCMAKE_PREFIX:FILEPATH="C:/projects/models"
    -DDEBUG=OFF -DPROFILE=OFF
    -DBUILD_PYTHON_BINDINGS=OFF
    -DCMAKE_BUILD_TYPE=Release ..

artifacts:
  - path: '**\*.zip'

notifications:
  - provider: Email
    to:
      - mlpack-git@lists.mlpack.org
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

cache:
  - packages -> **\packages.config
  - armadillo.tar.xz -> appveyor.yaml